site_name: PeTTa Documentation
site_description: "PeTTa — efficient MeTTa in Prolog. Docs, tutorials, language spec, and contributor guide."
site_author: "PeTTa contributors"
site_url: https://yabuz87.github.io/PeTTa_simple_docs/
repo_url: https://github.com/patham9/PeTTa
repo_name: PeTTa
edit_uri: edit/main/docs/

use_directory_urls: false  # ✅ Important: fixes 404 errors on GitHub Pages

theme:
  name: material
  features:
    - content.code.copy
    - navigation.instant
    - search.highlight
    - content.code.annotate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Standard Library:
      - Overview: standard-library/index.md
      - Arthimetic & Comparison: standard-library/arithmetic.md
      - Control Flow: standard-library/control-flow.md
      - Lists and Expr Operations: standard-library/list-operations.md
      - Higher-order predicates: standard-library/higher-order.md
      - space manipulation: standard-library/space.md
      - python Bindings: standard-library/python.md
  - what is new in PeTTa ?:
      - Lists and Expressions: standard-library/new/list.md
      - Python Binding: standard-library/new/py.md
      - Space Manipulation: standard-library/new/space.md
      - MORK: standard-library/new/mork.md
  # - PeTTa unsupported MeTTa functions (Contemporary):
  #    - Lists and Expressions: not-working/list.md
  #    - Math Operations: not-working/math.md
  #    - Error handling: not-working/error-handle.md
  #    - General functions: not-working/not-working-std-functions.md
  - Contributing: contributing.md

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yabuz87/PeTTa_docs
  generator: false  # Removes "Made with MkDocs" text
